/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.helper.MovingForm;
import java.awt.Color;

/**
 *
 * @author Thinh
 */
public class AccoutUserDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form AccoutUserDiaLog
     */
    public AccoutUserDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        MovingForm.initMoving(this, pnlAccAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAccAdmin = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRound2 = new com.ebooks.Compoment.PanelRound();
        imageBoder1 = new com.ebooks.Compoment.ImageBoder();
        jLabel1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelRound3 = new com.ebooks.Compoment.PanelRound();
        myButton1 = new com.ebooks.Compoment.MyButton();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlAccAdmin.setBackground(new java.awt.Color(254, 254, 254));
        pnlAccAdmin.setRoundBottomLeft(20);
        pnlAccAdmin.setRoundBottomRight(20);
        pnlAccAdmin.setRoundTopLeft(20);
        pnlAccAdmin.setRoundTopRight(20);
        pnlAccAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlAccAdmin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageBoder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/stock-photo-76398531.jpg"))); // NOI18N
        imageBoder1.setRadius(20);
        panelRound2.add(imageBoder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 250));
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel36.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Nerd cung cấp cho người dùng nhiều chức năng quản lý sách và đọc sách trên ");
        panelRound2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 610, 20));

        jLabel40.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("từ ứng dụng của Nerd mà không cần phải tốn thời gian đến thư viện hay mua");
        panelRound2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 600, 20));

        jLabel39.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Với khả năng đọc được sách ebook, bạn có thể tìm và đọc hàng ngàn sách ");
        panelRound2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 590, 20));

        jLabel38.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Nerd là một phần mềm quản lý thư viện online đầy đủ tính năng và tiện ích.");
        panelRound2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 570, 20));

        jLabel43.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("nhiều thiết bị khác nhau như máy tính, điện thoại di động và máy tính bảng.");
        panelRound2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 600, 20));

        jLabel19.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel19.setText("Thông Tin Về Ứng Dụng ");
        panelRound2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jTabbedPane1.addTab("Giới thiệu", panelRound2);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setBackground(new java.awt.Color(87, 190, 110));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Lưu Tài Khoản");
        myButton1.setBoderColor(new java.awt.Color(87, 190, 110));
        myButton1.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        panelRound3.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 220, 40));

        txtMatKhauMoi.setBackground(new java.awt.Color(222, 247, 227));
        txtMatKhauMoi.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRound3.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 360, 40));

        txtXacNhanMatKhau.setBackground(new java.awt.Color(222, 247, 227));
        txtXacNhanMatKhau.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRound3.add(txtXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 360, 40));

        jLabel24.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel24.setText("Xác Nhận");
        panelRound3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel23.setText("Mật Khẩu Mới ");
        panelRound3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRound3.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 360, 40));

        jLabel21.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel21.setText("Tên Đăng Nhập");
        panelRound3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtMatKhau.setBackground(new java.awt.Color(222, 247, 227));
        txtMatKhau.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRound3.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 360, 40));

        jLabel22.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel22.setText("Mật Khẩu");
        panelRound3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));
        panelRound3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 790, 10));

        jTabbedPane1.addTab("Đổi mật khẩu", panelRound3);

        pnlAccAdmin.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 890, 460));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlAccAdmin.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAccAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAccAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
       
    }//GEN-LAST:event_myButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccoutUserDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccoutUserDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccoutUserDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccoutUserDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccoutUserDiaLog dialog = new AccoutUserDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.ImageBoder imageBoder1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblExit1;
    private com.ebooks.Compoment.MyButton myButton1;
    private com.ebooks.Compoment.PanelRound panelRound2;
    private com.ebooks.Compoment.PanelRound panelRound3;
    private com.ebooks.Compoment.PanelRound pnlAccAdmin;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
