/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.helper.MovingForm;
import java.awt.Color;

/**
 *
 * @author Thinh
 */
public class AccoutAdmainDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form AccoutAdmainDiaLog
     */
    public AccoutAdmainDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        MovingForm.initMoving(this, pnlAccAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlAccAdmin = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        tabTaiKhoanAdmin = new javax.swing.JTabbedPane();
        pnlDanhSachTaiKhoan = new com.ebooks.Compoment.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTaiKhoan = new com.ebooks.Compoment.Table();
        panelRound4 = new com.ebooks.Compoment.PanelRound();
        txtTimTaiKhoan = new com.ebooks.Compoment.SearchText();
        btnTimTaiKhoan = new com.ebooks.Compoment.MyButton();
        btnLast = new com.ebooks.Compoment.MyButton();
        btnNext = new com.ebooks.Compoment.MyButton();
        btnPrev = new com.ebooks.Compoment.MyButton();
        btnFirst = new com.ebooks.Compoment.MyButton();
        pnlChiTietTaiKhoan = new com.ebooks.Compoment.PanelRound();
        lblGioiTinh = new javax.swing.JLabel();
        rdoNguoiDungThuong = new javax.swing.JRadioButton();
        rdoQuanTriVien = new javax.swing.JRadioButton();
        txtMaNguoiDung = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        btnLuuThongTin = new com.ebooks.Compoment.MyButton();
        btnXoaTaiKhoan = new com.ebooks.Compoment.MyButton();
        txtTenDangNhap = new javax.swing.JTextField();
        lblHoTen2 = new javax.swing.JLabel();
        txtMatKhau = new com.ebooks.Compoment.txtFieldPassBoder();
        lblHoTen3 = new javax.swing.JLabel();
        rdoDungHoatDong = new javax.swing.JRadioButton();
        rdoBinhThuong = new javax.swing.JRadioButton();
        lblGioiTinh1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAccAdmin.setBackground(new java.awt.Color(254, 254, 254));
        pnlAccAdmin.setRoundBottomLeft(20);
        pnlAccAdmin.setRoundBottomRight(20);
        pnlAccAdmin.setRoundTopLeft(20);
        pnlAccAdmin.setRoundTopRight(20);
        pnlAccAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlAccAdmin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tabTaiKhoanAdmin.setBackground(new java.awt.Color(255, 255, 255));
        tabTaiKhoanAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pnlDanhSachTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSachTaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTaiKhoan.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTaiKhoan.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblTaiKhoan);

        pnlDanhSachTaiKhoan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 850, 300));

        panelRound4.setBackground(new java.awt.Color(232, 244, 234));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimTaiKhoan.setBackground(new java.awt.Color(232, 244, 234));
        txtTimTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        txtTimTaiKhoan.setText("Tìm kiếm tài khoản ");
        txtTimTaiKhoan.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        panelRound4.add(txtTimTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));

        btnTimTaiKhoan.setBackground(new java.awt.Color(232, 244, 234));
        btnTimTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        btnTimTaiKhoan.setBoderColor(new java.awt.Color(232, 244, 234));
        btnTimTaiKhoan.setRadius(10);
        btnTimTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTaiKhoanActionPerformed(evt);
            }
        });
        panelRound4.add(btnTimTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        pnlDanhSachTaiKhoan.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        btnLast.setBackground(new java.awt.Color(145, 227, 168));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast.setRadius(10);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlDanhSachTaiKhoan.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        btnNext.setBackground(new java.awt.Color(145, 227, 168));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext.setRadius(10);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlDanhSachTaiKhoan.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnPrev.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev.setRadius(10);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlDanhSachTaiKhoan.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnFirst.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst.setRadius(10);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlDanhSachTaiKhoan.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        tabTaiKhoanAdmin.addTab("Danh sách tài khoản", pnlDanhSachTaiKhoan);

        pnlChiTietTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        pnlChiTietTaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGioiTinh.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblGioiTinh.setText("Vai trò");
        pnlChiTietTaiKhoan.add(lblGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        rdoNguoiDungThuong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdoNguoiDungThuong);
        rdoNguoiDungThuong.setSelected(true);
        rdoNguoiDungThuong.setText("Người dùng thường");
        rdoNguoiDungThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNguoiDungThuongActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(rdoNguoiDungThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        rdoQuanTriVien.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdoQuanTriVien);
        rdoQuanTriVien.setText("Quản trị viên");
        rdoQuanTriVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoQuanTriVienActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(rdoQuanTriVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        txtMaNguoiDung.setBackground(new java.awt.Color(222, 247, 227));
        pnlChiTietTaiKhoan.add(txtMaNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 247, 40));

        lblHoTen1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen1.setText("Mật khẩu");
        pnlChiTietTaiKhoan.add(lblHoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        btnLuuThongTin.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuThongTin.setText("Lưu thông tin ");
        btnLuuThongTin.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnLuuThongTin.setRadius(10);
        btnLuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongTinActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(btnLuuThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 200, 40));

        btnXoaTaiKhoan.setBackground(new java.awt.Color(255, 102, 102));
        btnXoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnXoaTaiKhoan.setBoderColor(new java.awt.Color(255, 102, 102));
        btnXoaTaiKhoan.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnXoaTaiKhoan.setRadius(10);
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(btnXoaTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 40, 40));

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        pnlChiTietTaiKhoan.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 40));

        lblHoTen2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen2.setText("Tên đăng nhập");
        pnlChiTietTaiKhoan.add(lblHoTen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtMatKhau.setBackground(new java.awt.Color(222, 247, 227));
        txtMatKhau.setText("txtFieldPassBoder1");
        pnlChiTietTaiKhoan.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 247, 40));

        lblHoTen3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen3.setText("Mã người dùng");
        pnlChiTietTaiKhoan.add(lblHoTen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        rdoDungHoatDong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoDungHoatDong);
        rdoDungHoatDong.setSelected(true);
        rdoDungHoatDong.setText("Dừng hoạt động");
        rdoDungHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDungHoatDongActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(rdoDungHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        rdoBinhThuong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoBinhThuong);
        rdoBinhThuong.setText("Bình thường");
        rdoBinhThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBinhThuongActionPerformed(evt);
            }
        });
        pnlChiTietTaiKhoan.add(rdoBinhThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        lblGioiTinh1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblGioiTinh1.setText("Trạng thái");
        pnlChiTietTaiKhoan.add(lblGioiTinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlChiTietTaiKhoan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 10, 70));
        pnlChiTietTaiKhoan.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 810, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlChiTietTaiKhoan.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 10, 70));

        tabTaiKhoanAdmin.addTab("Chi tiết tài khoản", pnlChiTietTaiKhoan);

        pnlAccAdmin.add(tabTaiKhoanAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 460));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlAccAdmin.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        getContentPane().add(pnlAccAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimTaiKhoanActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        //        int index = tblTacGia.getSelectedRow();
        //        UtilityHelper.last(index, tblTacGia, listTL);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        //        int index = tblTheLoai.getSelectedRow();
        //        UtilityHelper.next(index, tblTheLoai, listTL);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        //        int index = tblTheLoai.getSelectedRow();
        //        UtilityHelper.previous(index, tblTheLoai, listTL);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        //        int index = tblTheLoai.getSelectedRow();
        //        UtilityHelper.first(index, tblTheLoai);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuThongTinActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void rdoNguoiDungThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNguoiDungThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNguoiDungThuongActionPerformed

    private void rdoDungHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDungHoatDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDungHoatDongActionPerformed

    private void rdoQuanTriVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoQuanTriVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoQuanTriVienActionPerformed

    private void rdoBinhThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBinhThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBinhThuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccoutAdmainDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccoutAdmainDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccoutAdmainDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccoutAdmainDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccoutAdmainDiaLog dialog = new AccoutAdmainDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnFirst;
    private com.ebooks.Compoment.MyButton btnLast;
    private com.ebooks.Compoment.MyButton btnLuuThongTin;
    private com.ebooks.Compoment.MyButton btnNext;
    private com.ebooks.Compoment.MyButton btnPrev;
    private com.ebooks.Compoment.MyButton btnTimTaiKhoan;
    private com.ebooks.Compoment.MyButton btnXoaTaiKhoan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblGioiTinh1;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblHoTen3;
    private com.ebooks.Compoment.PanelRound panelRound4;
    private com.ebooks.Compoment.PanelRound pnlAccAdmin;
    private com.ebooks.Compoment.PanelRound pnlChiTietTaiKhoan;
    private com.ebooks.Compoment.PanelRound pnlDanhSachTaiKhoan;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JRadioButton rdoBinhThuong;
    private javax.swing.JRadioButton rdoDungHoatDong;
    private javax.swing.JRadioButton rdoNguoiDungThuong;
    private javax.swing.JRadioButton rdoQuanTriVien;
    private javax.swing.JTabbedPane tabTaiKhoanAdmin;
    private com.ebooks.Compoment.Table tblTaiKhoan;
    private javax.swing.JTextField txtMaNguoiDung;
    private com.ebooks.Compoment.txtFieldPassBoder txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private com.ebooks.Compoment.SearchText txtTimTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
