/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.helper.MovingForm;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Thinh
 */
public class AddTypeAndAuthorDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form AddTypeAndAuthorDiaLog
     */
    public AddTypeAndAuthorDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        MovingForm.initMoving(this, pnlTypeAndAuthor);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTypeAndAuthor = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlAddInfo = new com.ebooks.Compoment.PanelRound();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        lblSachImg = new com.ebooks.Compoment.ImageBoder();
        lblMaSach = new javax.swing.JLabel();
        lblTenSach1 = new javax.swing.JLabel();
        btnChonSach = new com.ebooks.Compoment.MyButton();
        txtDuongDan = new javax.swing.JTextField();
        lblTenSach2 = new javax.swing.JLabel();
        cboNhaXuatBan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheLoai = new com.ebooks.Compoment.Table();
        lblTenSach3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTacGia = new com.ebooks.Compoment.Table();
        lblTenSach4 = new javax.swing.JLabel();
        btnHuyBoTheLoai = new com.ebooks.Compoment.MyButton();
        btnThemTheLoai = new com.ebooks.Compoment.MyButton();
        btnThemTacGia = new com.ebooks.Compoment.MyButton();
        btnHuyBoTacGia = new com.ebooks.Compoment.MyButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlTypeAndAuthor.setBackground(new java.awt.Color(254, 254, 254));
        pnlTypeAndAuthor.setPreferredSize(new java.awt.Dimension(910, 550));
        pnlTypeAndAuthor.setRoundBottomLeft(20);
        pnlTypeAndAuthor.setRoundBottomRight(20);
        pnlTypeAndAuthor.setRoundTopLeft(20);
        pnlTypeAndAuthor.setRoundTopRight(20);
        pnlTypeAndAuthor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlTypeAndAuthor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlTypeAndAuthor.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        jScrollPane1.setBorder(null);

        pnlAddInfo.setBackground(new java.awt.Color(249, 249, 249));
        pnlAddInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaSach.setBackground(new java.awt.Color(222, 247, 227));
        txtMaSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaSachKeyPressed(evt);
            }
        });
        pnlAddInfo.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 260, 40));

        txtTenSach.setBackground(new java.awt.Color(222, 247, 227));
        txtTenSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenSachKeyPressed(evt);
            }
        });
        pnlAddInfo.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 260, 40));

        lblSachImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/stock-photo-76398531.jpg"))); // NOI18N
        lblSachImg.setRadius(20);
        lblSachImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSachImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSachImgMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSachImgMousePressed(evt);
            }
        });
        pnlAddInfo.add(lblSachImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 200));

        lblMaSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaSach.setText("Mã Sách");
        pnlAddInfo.add(lblMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblTenSach1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach1.setText("Tên Sách");
        pnlAddInfo.add(lblTenSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnChonSach.setBackground(new java.awt.Color(87, 190, 110));
        btnChonSach.setForeground(new java.awt.Color(255, 255, 255));
        btnChonSach.setText("Chọn Sách");
        btnChonSach.setBoderColor(new java.awt.Color(87, 190, 110));
        btnChonSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnChonSach.setRadius(10);
        btnChonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonSachActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnChonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 200, 40));

        txtDuongDan.setBackground(new java.awt.Color(222, 247, 227));
        pnlAddInfo.add(txtDuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 260, 40));

        lblTenSach2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach2.setText("Thể loại của sách");
        pnlAddInfo.add(lblTenSach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        cboNhaXuatBan.setBackground(new java.awt.Color(222, 247, 227));
        cboNhaXuatBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboNhaXuatBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cboNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhaXuatBanActionPerformed(evt);
            }
        });
        pnlAddInfo.add(cboNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 260, 40));

        jLabel3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel3.setText("Mã Nhà Xuẩt Bản");
        pnlAddInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTheLoai.setSelectionBackground(new java.awt.Color(87, 190, 110));
        jScrollPane2.setViewportView(tblTheLoai);

        pnlAddInfo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 390, 190));

        lblTenSach3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach3.setText("File PDF");
        pnlAddInfo.add(lblTenSach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        tblTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTacGia.setSelectionBackground(new java.awt.Color(87, 190, 110));
        jScrollPane3.setViewportView(tblTacGia);

        pnlAddInfo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 390, 190));

        lblTenSach4.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenSach4.setText("Tác giả của sách");
        pnlAddInfo.add(lblTenSach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        btnHuyBoTheLoai.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyBoTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBoTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnHuyBoTheLoai.setText("Hủy bỏ");
        btnHuyBoTheLoai.setBoderColor(new java.awt.Color(255, 102, 102));
        btnHuyBoTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnHuyBoTheLoai.setRadius(10);
        btnHuyBoTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoTheLoaiActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnHuyBoTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 110, 40));

        btnThemTheLoai.setBackground(new java.awt.Color(87, 190, 110));
        btnThemTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/add-document.png"))); // NOI18N
        btnThemTheLoai.setText("Thêm thể loại");
        btnThemTheLoai.setBoderColor(new java.awt.Color(87, 190, 110));
        btnThemTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnThemTheLoai.setRadius(10);
        btnThemTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTheLoaiActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnThemTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 160, 40));

        btnThemTacGia.setBackground(new java.awt.Color(87, 190, 110));
        btnThemTacGia.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/user-add (1).png"))); // NOI18N
        btnThemTacGia.setText("Tác giả");
        btnThemTacGia.setBoderColor(new java.awt.Color(87, 190, 110));
        btnThemTacGia.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnThemTacGia.setRadius(10);
        btnThemTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTacGiaActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnThemTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 160, 40));

        btnHuyBoTacGia.setBackground(new java.awt.Color(255, 102, 102));
        btnHuyBoTacGia.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBoTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnHuyBoTacGia.setText("Hủy bỏ");
        btnHuyBoTacGia.setBoderColor(new java.awt.Color(255, 102, 102));
        btnHuyBoTacGia.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnHuyBoTacGia.setRadius(10);
        btnHuyBoTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoTacGiaActionPerformed(evt);
            }
        });
        pnlAddInfo.add(btnHuyBoTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 40));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlAddInfo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, 10));

        jScrollPane1.setViewportView(pnlAddInfo);

        pnlTypeAndAuthor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 910, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTypeAndAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTypeAndAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void btnChonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonSachActionPerformed
       new ListBookDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_btnChonSachActionPerformed

    private void lblSachImgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachImgMousePressed
        if (evt.getClickCount() == 2) {
            try {

            } catch (Exception e) {
                //               DialogHelper.alert(this,"Lỗi Chọn Hình");
            }
        }
    }//GEN-LAST:event_lblSachImgMousePressed

    private void lblSachImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachImgMouseExited

    }//GEN-LAST:event_lblSachImgMouseExited

    private void lblSachImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSachImgMouseEntered

    }//GEN-LAST:event_lblSachImgMouseEntered

    private void txtTenSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSachKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtTenSachKeyPressed

    private void txtMaSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtMaSachKeyPressed

    private void cboNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhaXuatBanActionPerformed

    }//GEN-LAST:event_cboNhaXuatBanActionPerformed

    private void btnHuyBoTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyBoTheLoaiActionPerformed

    private void btnThemTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTheLoaiActionPerformed
         new ListTypeBookDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_btnThemTheLoaiActionPerformed

    private void btnThemTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTacGiaActionPerformed
        new ListAuthorDiaLog(this, true).setVisible(true);
    }//GEN-LAST:event_btnThemTacGiaActionPerformed

    private void btnHuyBoTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyBoTacGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTypeAndAuthorDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTypeAndAuthorDiaLog dialog = new AddTypeAndAuthorDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnChonSach;
    private com.ebooks.Compoment.MyButton btnHuyBoTacGia;
    private com.ebooks.Compoment.MyButton btnHuyBoTheLoai;
    private com.ebooks.Compoment.MyButton btnThemTacGia;
    private com.ebooks.Compoment.MyButton btnThemTheLoai;
    private javax.swing.JComboBox<String> cboNhaXuatBan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblMaSach;
    private com.ebooks.Compoment.ImageBoder lblSachImg;
    private javax.swing.JLabel lblTenSach1;
    private javax.swing.JLabel lblTenSach2;
    private javax.swing.JLabel lblTenSach3;
    private javax.swing.JLabel lblTenSach4;
    private com.ebooks.Compoment.PanelRound pnlAddInfo;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private com.ebooks.Compoment.PanelRound pnlTypeAndAuthor;
    private com.ebooks.Compoment.Table tblTacGia;
    private com.ebooks.Compoment.Table tblTheLoai;
    private javax.swing.JTextField txtDuongDan;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
