/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import com.ebooks.helper.MovingForm;
import java.awt.Color;
import java.text.SimpleDateFormat;
public class ProfileDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProfileDialog
     */
    
     boolean congTac;
        
    public ProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        MovingForm.initMoving(this, pnlInfoUser);
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfoUser = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        lblAnhDaiDien = new com.ebooks.Compoment.ImageAvatar();
        jLabel21 = new javax.swing.JLabel();
        txtHoTenNguoiDung = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNgaySinhNguoiDung = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        cboGioiTin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaNguoiDung = new javax.swing.JTextArea();
        lblMoTa = new javax.swing.JLabel();
        btnLuuThongTin = new com.ebooks.Compoment.MyButton();
        btnIconCld = new com.ebooks.Compoment.MyButton();
        Calendar = new com.toedter.calendar.JCalendar();
        txtTenDangNhap = new javax.swing.JTextField();
        lblGioiTinh1 = new javax.swing.JLabel();
        txtDiaChiEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlInfoUser.setBackground(new java.awt.Color(254, 254, 254));
        pnlInfoUser.setRoundBottomLeft(20);
        pnlInfoUser.setRoundBottomRight(20);
        pnlInfoUser.setRoundTopLeft(20);
        pnlInfoUser.setRoundTopRight(20);
        pnlInfoUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlInfoUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlInfoUser.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        lblAnhDaiDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/41b92ec3eab97e4c24b3f6e8fe75ddec.png"))); // NOI18N
        pnlInfoUser.add(lblAnhDaiDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 110));

        jLabel21.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel21.setText("Ảnh đại diện");
        pnlInfoUser.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 30));

        txtHoTenNguoiDung.setBackground(new java.awt.Color(222, 247, 227));
        txtHoTenNguoiDung.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pnlInfoUser.add(txtHoTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 290, 40));

        jLabel22.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel22.setText("Họ tên của bạn");
        pnlInfoUser.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        txtNgaySinhNguoiDung.setBackground(new java.awt.Color(222, 247, 227));
        txtNgaySinhNguoiDung.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pnlInfoUser.add(txtNgaySinhNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 240, 40));

        jLabel23.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel23.setText("Ngày sinh");
        pnlInfoUser.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        txtSoDienThoai.setBackground(new java.awt.Color(222, 247, 227));
        txtSoDienThoai.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pnlInfoUser.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 290, 40));

        jLabel24.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel24.setText("Số điện thoại");
        pnlInfoUser.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        lblGioiTinh.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblGioiTinh.setText("Giới Tính");
        pnlInfoUser.add(lblGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        cboGioiTin.setBackground(new java.awt.Color(222, 247, 227));
        cboGioiTin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlInfoUser.add(cboGioiTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 290, 40));

        txtMoTaNguoiDung.setColumns(20);
        txtMoTaNguoiDung.setRows(5);
        jScrollPane1.setViewportView(txtMoTaNguoiDung);

        pnlInfoUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 810, 100));

        lblMoTa.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMoTa.setText("Mô Tả");
        pnlInfoUser.add(lblMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, -1));

        btnLuuThongTin.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuThongTin.setText("Lưu thông tin ");
        btnLuuThongTin.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnLuuThongTin.setRadius(10);
        btnLuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongTinActionPerformed(evt);
            }
        });
        pnlInfoUser.add(btnLuuThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 200, 40));

        btnIconCld.setBackground(new java.awt.Color(87, 190, 110));
        btnIconCld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/calendar.png"))); // NOI18N
        btnIconCld.setAutoscrolls(true);
        btnIconCld.setBoderColor(new java.awt.Color(204, 204, 204));
        btnIconCld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconCldActionPerformed(evt);
            }
        });
        pnlInfoUser.add(btnIconCld, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 50, 40));

        Calendar.setBackground(new java.awt.Color(201, 235, 201));
        Calendar.setDecorationBackgroundColor(new java.awt.Color(153, 255, 153));
        Calendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        Calendar.setWeekdayForeground(new java.awt.Color(51, 51, 51));
        Calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarPropertyChange(evt);
            }
        });
        pnlInfoUser.add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pnlInfoUser.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 290, 40));

        lblGioiTinh1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblGioiTinh1.setText("Tên đăng nhập");
        pnlInfoUser.add(lblGioiTinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        txtDiaChiEmail.setBackground(new java.awt.Color(222, 247, 227));
        txtDiaChiEmail.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        pnlInfoUser.add(txtDiaChiEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 290, 40));

        jLabel25.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel25.setText("Địa chỉ email");
        pnlInfoUser.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void btnLuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuThongTinActionPerformed

    private void btnIconCldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconCldActionPerformed
       
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }//GEN-LAST:event_btnIconCldActionPerformed

    private void CalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarPropertyChange
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        txtNgaySinhNguoiDung.setText(String.valueOf(formats.format(Calendar.getDate())));
    }//GEN-LAST:event_CalendarPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfileDialog dialog = new ProfileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private com.ebooks.Compoment.MyButton btnIconCld;
    private com.ebooks.Compoment.MyButton btnLuuThongTin;
    private javax.swing.JComboBox<String> cboGioiTin;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ebooks.Compoment.ImageAvatar lblAnhDaiDien;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblGioiTinh1;
    private javax.swing.JLabel lblMoTa;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private com.ebooks.Compoment.PanelRound pnlInfoUser;
    private javax.swing.JTextField txtDiaChiEmail;
    private javax.swing.JTextField txtHoTenNguoiDung;
    private javax.swing.JTextArea txtMoTaNguoiDung;
    private javax.swing.JTextField txtNgaySinhNguoiDung;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
