/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebook.mainFrame;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thinh
 */
public class TypeBookDiaLog extends javax.swing.JDialog {

     boolean congTac = false;
    public TypeBookDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.ebooks.Compoment.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        TabPneTheLoai = new javax.swing.JTabbedPane();
        tabDanhSachTheLoai = new com.ebooks.Compoment.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheLoai = new com.ebooks.Compoment.Table();
        panelRound4 = new com.ebooks.Compoment.PanelRound();
        txtTimTheLoai = new com.ebooks.Compoment.SearchText();
        btnTimTheLoai = new com.ebooks.Compoment.MyButton();
        btnFirst = new com.ebooks.Compoment.MyButton();
        btnPrev = new com.ebooks.Compoment.MyButton();
        btnNext = new com.ebooks.Compoment.MyButton();
        btnLast = new com.ebooks.Compoment.MyButton();
        tabThongTinTheLoai = new com.ebooks.Compoment.PanelRound();
        txtMaTheLoai = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtNgayĐăng = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        btnIconCld = new com.ebooks.Compoment.MyButton();
        Calendar = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaTheLoai = new javax.swing.JTextArea();
        lblMoTa = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        btnXoaTheLoai = new com.ebooks.Compoment.MyButton();
        txtTenTheLoai = new javax.swing.JTextField();
        lblHoTen2 = new javax.swing.JLabel();
        btnLuuThongTin = new com.ebooks.Compoment.MyButton();
        btnClearForm = new com.ebooks.Compoment.MyButton();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(254, 254, 254));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TabPneTheLoai.setBackground(new java.awt.Color(255, 255, 255));
        TabPneTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tabDanhSachTheLoai.setBackground(new java.awt.Color(255, 255, 255));
        tabDanhSachTheLoai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTheLoai.setSelectionBackground(new java.awt.Color(87, 190, 110));
        tblTheLoai.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblTheLoai);

        tabDanhSachTheLoai.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 850, 300));

        panelRound4.setBackground(new java.awt.Color(232, 244, 234));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimTheLoai.setBackground(new java.awt.Color(232, 244, 234));
        txtTimTheLoai.setForeground(new java.awt.Color(51, 51, 51));
        txtTimTheLoai.setText("Tìm kiếm thể loại ");
        txtTimTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        txtTimTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTheLoaiActionPerformed(evt);
            }
        });
        panelRound4.add(txtTimTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 40));

        btnTimTheLoai.setBackground(new java.awt.Color(232, 244, 234));
        btnTimTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        btnTimTheLoai.setBoderColor(new java.awt.Color(232, 244, 234));
        btnTimTheLoai.setRadius(10);
        btnTimTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheLoaiActionPerformed(evt);
            }
        });
        panelRound4.add(btnTimTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        tabDanhSachTheLoai.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        btnFirst.setBackground(new java.awt.Color(145, 227, 168));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-left.png"))); // NOI18N
        btnFirst.setBoderColor(new java.awt.Color(145, 227, 168));
        btnFirst.setRadius(10);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        tabDanhSachTheLoai.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 60, 40));

        btnPrev.setBackground(new java.awt.Color(145, 227, 168));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-left.png"))); // NOI18N
        btnPrev.setBoderColor(new java.awt.Color(145, 227, 168));
        btnPrev.setRadius(10);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        tabDanhSachTheLoai.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 40));

        btnNext.setBackground(new java.awt.Color(145, 227, 168));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/caret-right.png"))); // NOI18N
        btnNext.setBoderColor(new java.awt.Color(145, 227, 168));
        btnNext.setRadius(10);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        tabDanhSachTheLoai.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 60, 40));

        btnLast.setBackground(new java.awt.Color(145, 227, 168));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/angle-double-small-right.png"))); // NOI18N
        btnLast.setBoderColor(new java.awt.Color(145, 227, 168));
        btnLast.setRadius(10);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        tabDanhSachTheLoai.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 60, 40));

        TabPneTheLoai.addTab("Danh sách thể loại", tabDanhSachTheLoai);

        tabThongTinTheLoai.setBackground(new java.awt.Color(255, 255, 255));
        tabThongTinTheLoai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaTheLoai.setBackground(new java.awt.Color(222, 247, 227));
        tabThongTinTheLoai.add(txtMaTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 360, 40));

        lblHoTen.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen.setText("Mã thể loại");
        tabThongTinTheLoai.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtNgayĐăng.setBackground(new java.awt.Color(222, 247, 227));
        tabThongTinTheLoai.add(txtNgayĐăng, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 310, 40));

        lblNgaySinh.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblNgaySinh.setText("Ngày đăng");
        tabThongTinTheLoai.add(lblNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        btnIconCld.setBackground(new java.awt.Color(87, 190, 110));
        btnIconCld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/calendar.png"))); // NOI18N
        btnIconCld.setAutoscrolls(true);
        btnIconCld.setBoderColor(new java.awt.Color(204, 204, 204));
        btnIconCld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconCldActionPerformed(evt);
            }
        });
        tabThongTinTheLoai.add(btnIconCld, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 50, 40));

        Calendar.setBackground(new java.awt.Color(201, 235, 201));
        Calendar.setDecorationBackgroundColor(new java.awt.Color(153, 255, 153));
        Calendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        Calendar.setWeekdayForeground(new java.awt.Color(51, 51, 51));
        Calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarPropertyChange(evt);
            }
        });
        tabThongTinTheLoai.add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        txtMoTaTheLoai.setColumns(20);
        txtMoTaTheLoai.setRows(5);
        jScrollPane1.setViewportView(txtMoTaTheLoai);

        tabThongTinTheLoai.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 790, 100));

        lblMoTa.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMoTa.setText("Mô tả thể loại");
        tabThongTinTheLoai.add(lblMoTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, -1));

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        tabThongTinTheLoai.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 360, 40));

        lblHoTen1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen1.setText("Tên tài khoản đăng");
        tabThongTinTheLoai.add(lblHoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        btnXoaTheLoai.setBackground(new java.awt.Color(255, 102, 102));
        btnXoaTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/circle-cross.png"))); // NOI18N
        btnXoaTheLoai.setBoderColor(new java.awt.Color(255, 102, 102));
        btnXoaTheLoai.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnXoaTheLoai.setRadius(10);
        btnXoaTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTheLoaiActionPerformed(evt);
            }
        });
        tabThongTinTheLoai.add(btnXoaTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 40, 40));

        txtTenTheLoai.setBackground(new java.awt.Color(222, 247, 227));
        tabThongTinTheLoai.add(txtTenTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 360, 40));

        lblHoTen2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblHoTen2.setText("Tên thể loại");
        tabThongTinTheLoai.add(lblHoTen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnLuuThongTin.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuThongTin.setText("Lưu thông tin ");
        btnLuuThongTin.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuThongTin.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnLuuThongTin.setRadius(10);
        btnLuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongTinActionPerformed(evt);
            }
        });
        tabThongTinTheLoai.add(btnLuuThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 200, 40));

        btnClearForm.setBackground(new java.awt.Color(87, 190, 110));
        btnClearForm.setForeground(new java.awt.Color(255, 255, 255));
        btnClearForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/add-document.png"))); // NOI18N
        btnClearForm.setBoderColor(new java.awt.Color(87, 190, 110));
        btnClearForm.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        btnClearForm.setRadius(10);
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });
        tabThongTinTheLoai.add(btnClearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 40, 40));

        TabPneTheLoai.addTab("Thông Tin thể loại", tabThongTinTheLoai);

        panelRound1.add(TabPneTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 460));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(20);
        pnlExit1.setRoundTopRight(20);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExit1MousePressed(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        panelRound1.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimTheLoaiActionPerformed

    private void btnIconCldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconCldActionPerformed
        Calendar.setVisible(congTac);
        congTac = !congTac;
    }//GEN-LAST:event_btnIconCldActionPerformed

    private void CalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarPropertyChange
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        txtNgayĐăng.setText(String.valueOf(formats.format(Calendar.getDate())));
    }//GEN-LAST:event_CalendarPropertyChange

    private void btnXoaTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaTheLoaiActionPerformed

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExit1MouseClicked

    private void lblExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExit1MousePressed

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlExit1MousePressed

    private void txtTimTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimTheLoaiActionPerformed

    private void btnLuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuThongTinActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
//        int index = tblTheLoai.getSelectedRow();
//        UtilityHelper.first(index, tblTheLoai);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
//        int index = tblTheLoai.getSelectedRow();
//        UtilityHelper.previous(index, tblTheLoai, listTL);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
//        int index = tblTheLoai.getSelectedRow();
//        UtilityHelper.next(index, tblTheLoai, listTL);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
//        int index = tblTheLoai.getSelectedRow();
//        UtilityHelper.last(index, tblTheLoai, listTL);
    }//GEN-LAST:event_btnLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypeBookDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypeBookDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypeBookDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypeBookDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TypeBookDiaLog dialog = new TypeBookDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JTabbedPane TabPneTheLoai;
    private com.ebooks.Compoment.MyButton btnClearForm;
    private com.ebooks.Compoment.MyButton btnFirst;
    private com.ebooks.Compoment.MyButton btnIconCld;
    private com.ebooks.Compoment.MyButton btnLast;
    private com.ebooks.Compoment.MyButton btnLuuThongTin;
    private com.ebooks.Compoment.MyButton btnNext;
    private com.ebooks.Compoment.MyButton btnPrev;
    private com.ebooks.Compoment.MyButton btnTimTheLoai;
    private com.ebooks.Compoment.MyButton btnXoaTheLoai;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblNgaySinh;
    private com.ebooks.Compoment.PanelRound panelRound1;
    private com.ebooks.Compoment.PanelRound panelRound4;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private com.ebooks.Compoment.PanelRound tabDanhSachTheLoai;
    private com.ebooks.Compoment.PanelRound tabThongTinTheLoai;
    private com.ebooks.Compoment.Table tblTheLoai;
    private javax.swing.JTextField txtMaTheLoai;
    private javax.swing.JTextArea txtMoTaTheLoai;
    private javax.swing.JTextField txtNgayĐăng;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTenTheLoai;
    private com.ebooks.Compoment.SearchText txtTimTheLoai;
    // End of variables declaration//GEN-END:variables
}
